// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dhldqbcnyhlwhfflaolw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRobGRxYmNueWhsd2hmZmxhb2x3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3NjE0NzcsImV4cCI6MjA3MzMzNzQ3N30.lui-KK8CoHSVCCeJThsY3qTme69Pw0LkNqvgDZAOfgs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});